"""Fixtures for the real-Telegram E2E layer.

These tests use Telethon as a *user-account* MTProto client and drive a
real `finance bot` subprocess against the real Telegram servers. They are
strictly opt-in: anything missing in the credential bundle skips the whole
file rather than failing.

Credentials come from two places, by design:

  1. Telethon-side (your USER account), in `.telegram-test-secrets.toml`
     at the repo root, generated by `scripts/telethon_auth.py`:
       api_id, api_hash, session_string, user_id

  2. Bot-side (the actual bot under test), loaded the same way `finance bot`
     itself loads them — via `Settings.load()`, which reads
     `~/.finance/config.toml` (+ FINANCE_* env overrides). The bot token
     and allow-list are NOT duplicated into the test secrets file; the
     test uses whatever bot you've already configured.

The bot's `@username` is looked up at fixture-setup time via the Telegram
`getMe` API, so there's nothing to maintain on that front either.

Each test gets a fresh `FINANCE_HOME` (so the user's real DB is untouched),
but the bot itself is the same bot you run in production. Test runs DO
leave messages in the real chat history with that bot.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import time
import tomllib
from collections.abc import AsyncIterator, Iterator
from pathlib import Path
from typing import Any

import httpx
import pytest
import tomli_w

REPO_ROOT = Path(__file__).resolve().parents[2]
SECRETS_FILE = REPO_ROOT / ".telegram-test-secrets.toml"


def _load_telethon_creds() -> dict[str, Any] | None:
    """Telethon (USER-account) credentials from the secrets file + env.

    These are the only secrets specific to this test layer. The bot's own
    token and allow-list are NOT loaded here — see `_load_bot_creds`.
    """
    creds: dict[str, Any] = {}
    if SECRETS_FILE.exists():
        with SECRETS_FILE.open("rb") as f:
            creds.update(tomllib.load(f))

    env_map = {
        "TELEGRAM_API_ID": ("api_id", int),
        "TELEGRAM_API_HASH": ("api_hash", str),
        "TELEGRAM_SESSION_STRING": ("session_string", str),
    }
    for env_name, (key, coerce) in env_map.items():
        v = os.environ.get(env_name)
        if v:
            creds[key] = coerce(v)

    required = ("api_id", "api_hash", "session_string")
    if any(k not in creds or creds[k] in (None, "") for k in required):
        return None
    creds["api_id"] = int(creds["api_id"])
    return creds


def _load_bot_creds() -> dict[str, Any] | None:
    """Bot-side credentials, loaded the same way `finance bot` itself loads
    them — `Settings.load()` reads `~/.finance/config.toml` plus FINANCE_*
    env overrides. Single source of truth, no duplication."""
    from finance.core.config import Settings

    s = Settings.load()
    if not s.telegram.token or not s.telegram.allow_list:
        return None
    return {
        "bot_token": s.telegram.token,
        "bot_allow_list": [int(c) for c in s.telegram.allow_list],
    }


def _resolve_bot_username(bot_token: str) -> str | None:
    """Look up the bot's `@username` via the Telegram `getMe` API.

    Avoids duplicating the username into config; whatever bot is configured
    is the bot the test talks to.
    """
    try:
        r = httpx.get(f"https://api.telegram.org/bot{bot_token}/getMe", timeout=10.0)
        r.raise_for_status()
        return r.json()["result"].get("username")
    except (httpx.HTTPError, KeyError, ValueError):
        return None


@pytest.fixture(scope="session")
def e2e_creds() -> dict[str, Any]:
    telethon = _load_telethon_creds()
    if telethon is None:
        pytest.skip(
            "E2E Telegram tests need .telegram-test-secrets.toml. Run "
            "`uv run python scripts/telethon_auth.py` to produce it."
        )

    bot = _load_bot_creds()
    if bot is None:
        pytest.skip(
            "E2E Telegram tests need a configured bot. Set "
            "telegram.token and telegram.allow_list in ~/.finance/config.toml "
            "(or via FINANCE_TELEGRAM__* env vars)."
        )

    username = _resolve_bot_username(bot["bot_token"])
    if not username:
        pytest.skip(
            "Could not resolve bot @username via Telegram getMe — token "
            "may be invalid or network is unreachable."
        )

    user_id = telethon.get("user_id")
    if user_id is None:
        pytest.skip("Telethon secrets file is missing `user_id`; re-run scripts/telethon_auth.py.")
    user_id = int(user_id)
    if user_id not in bot["bot_allow_list"]:
        pytest.fail(
            f"Telethon user (id={user_id}) is not in the bot's allow_list "
            f"({bot['bot_allow_list']}). The bot would silently drop every "
            f"message from this account. Add the id with: "
            f"`uv run finance config set telegram.allow_list {user_id}`"
        )

    return {
        **telethon,
        **bot,
        "bot_username": username,
        "allowed_chat": user_id,
    }


def _run_or_fail(
    cmd: list[str], env: dict[str, str], timeout: float = 30.0
) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        cmd, env=env, capture_output=True, text=True, timeout=timeout, check=False
    )
    if result.returncode != 0:
        pytest.fail(
            f"command {cmd[1:]} failed (exit {result.returncode})\n"
            f"--- stdout ---\n{result.stdout}\n--- stderr ---\n{result.stderr}"
        )
    return result


def _drop_pending_bot_updates(bot_token: str) -> None:
    """Consume any pending updates so the bot starts fresh.

    Without this, a bot replying to backlog messages from previous test
    runs would land first in our Conversation and break assertions. The
    Bot API drops everything <= `offset-1`, so we read the latest
    `update_id` and re-call with `offset=last+1`.
    """
    base = f"https://api.telegram.org/bot{bot_token}"
    try:
        r = httpx.get(f"{base}/getUpdates", params={"timeout": 0}, timeout=10.0)
        r.raise_for_status()
        updates = r.json().get("result", [])
        if updates:
            last_id = int(updates[-1]["update_id"])
            httpx.get(
                f"{base}/getUpdates",
                params={"offset": last_id + 1, "timeout": 0},
                timeout=10.0,
            )
    except httpx.HTTPError:
        # Network/Telegram trouble pre-test is its own signal; let the
        # bot_process fixture surface it via the "bot ready" timeout.
        pass


def _write_bot_config(home: Path, creds: dict[str, Any]) -> Path:
    """Write a config.toml under `home` with the bot token + allow-list.

    Mode 0600 mirrors how the CLI's `config set` writes the file. We copy
    the full allow_list from the user's config so the test bot behaves
    identically to the real one.
    """
    config: dict[str, Any] = {
        "telegram": {
            "token": creds["bot_token"],
            "allow_list": list(creds["bot_allow_list"]),
        },
        "log": {"level": "INFO"},
    }
    path = home / "config.toml"
    path.write_text(tomli_w.dumps(config))
    path.chmod(0o600)
    return path


@pytest.fixture
def bot_process(
    e2e_creds: dict[str, Any], tmp_path: Path
) -> Iterator[tuple[subprocess.Popen[bytes], Path]]:
    """Spawn `finance bot` with an isolated FINANCE_HOME; wait for "bot ready".

    Yields `(process, log_file)`. The fixture creates one default account
    (`E2E Test EUR`) before starting the bot, so the PDF-upload picker flow
    has a target to pick.

    On startup failure, the captured bot output is attached to the failure
    message — the whole point of this test layer is making silent failures
    loud.
    """
    finance_bin = shutil.which("finance")
    if not finance_bin:
        pytest.fail("`finance` not on PATH. Run tests via `uv run pytest` or activate the venv.")

    home = tmp_path / "bot-home"
    home.mkdir()
    _write_bot_config(home, e2e_creds)

    env = {**os.environ, "FINANCE_HOME": str(home)}

    # Drop any updates left over from a previous bot/test run so the new
    # bot doesn't reply to stale messages.
    _drop_pending_bot_updates(e2e_creds["bot_token"])

    _run_or_fail([finance_bin, "init"], env)
    _run_or_fail(
        [
            finance_bin,
            "account",
            "create",
            "--name",
            "E2E Test EUR",
            "--currency",
            "EUR",
        ],
        env,
    )

    log_file = home / "bot.log"
    log_handle = log_file.open("wb")
    proc = subprocess.Popen(
        [finance_bin, "bot"],
        env=env,
        stdout=log_handle,
        stderr=subprocess.STDOUT,
    )

    deadline = time.time() + 30
    ready = False
    while time.time() < deadline:
        if proc.poll() is not None:
            break
        try:
            content = log_file.read_text()
        except FileNotFoundError:
            content = ""
        if "bot ready" in content:
            ready = True
            break
        time.sleep(0.25)

    if not ready:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait()
        log_handle.close()
        captured = log_file.read_text() if log_file.exists() else "(no output captured)"
        pytest.fail(
            f"`finance bot` did not log 'bot ready' within 30s "
            f"(exit code: {proc.returncode}).\n"
            f"--- bot stdout/stderr ---\n{captured}"
        )

    try:
        yield proc, log_file
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait()
        log_handle.close()


@pytest.fixture
async def tg_client(e2e_creds: dict[str, Any]) -> AsyncIterator[Any]:
    """Connected Telethon user-account client.

    Function-scoped: connect/disconnect per test (~1s overhead). Avoids the
    pytest-asyncio session-scope event-loop hassle.
    """
    from telethon import TelegramClient
    from telethon.sessions import StringSession

    client = TelegramClient(
        StringSession(e2e_creds["session_string"]),
        int(e2e_creds["api_id"]),
        e2e_creds["api_hash"],
    )
    await client.connect()
    if not await client.is_user_authorized():
        pytest.skip(
            "Stored Telethon session is not authorized; re-run scripts/telethon_auth.py to refresh."
        )

    try:
        yield client
    finally:
        await client.disconnect()


@pytest.fixture
def wise_pdf() -> Path:
    """Path to a real Wise PDF fixture used for the upload tests."""
    pdf = Path(__file__).resolve().parents[1] / "fixtures" / "wise" / "april_2026.pdf"
    if not pdf.is_file():
        pytest.skip(f"wise fixture pdf not present at {pdf}")
    return pdf


def _format_bot_log_tail(log_file: Path, n_lines: int = 80) -> str:
    """Last `n_lines` of the bot's log file, for failure-message context."""
    if not log_file.exists():
        return "(no log file)"
    lines = log_file.read_text().splitlines()
    return "\n".join(lines[-n_lines:])


@pytest.fixture
def bot_log_tail(
    bot_process: tuple[subprocess.Popen[bytes], Path],
) -> Any:
    """Callable that returns the tail of the bot's stdout, for assertions
    and for failure-message context."""
    _, log_file = bot_process

    def _tail(n_lines: int = 80) -> str:
        return _format_bot_log_tail(log_file, n_lines)

    return _tail


# Make conv-style helper available without per-test imports.
async def send_and_get_reply(client: Any, bot: str, text: str, timeout: float = 20.0) -> Any:
    """Send `text` to `bot` and return the bot's first reply Message.

    Uses Telethon's `Conversation` so we don't get tripped up by stale
    messages from previous test runs.
    """
    async with client.conversation(bot, timeout=timeout) as conv:
        await conv.send_message(text)
        return await conv.get_response()


__all__ = [
    "send_and_get_reply",
]
