"""One-time Telethon auth: produce a `StringSession` for E2E tests.

Run this ONCE on a machine with terminal access. It:

1. Reads `TELEGRAM_API_ID` and `TELEGRAM_API_HASH` from the environment.
2. Prompts for your phone number, the SMS/Telegram code, and (if you have it
   enabled) your 2FA password.
3. Authenticates against Telegram and captures the resulting session as a
   `StringSession` — a single opaque string that lets future test runs
   re-authenticate without ever touching the phone-code flow again.
4. Writes the session string to `<repo>/.telegram-test-secrets.toml`
   (gitignored), and ALSO prints export commands you can paste into your
   shell or a CI secrets store.

The session string is **as sensitive as your password**. If it leaks,
revoke it immediately at https://my.telegram.org → "API development tools" →
"Active sessions", or by signing out from any Telegram client.

Usage:

    export TELEGRAM_API_ID=12345
    export TELEGRAM_API_HASH=abcdef...
    uv run python scripts/telethon_auth.py
"""

from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path
from textwrap import dedent

from telethon import TelegramClient
from telethon.sessions import StringSession

REPO_ROOT = Path(__file__).resolve().parent.parent
SECRETS_FILE = REPO_ROOT / ".telegram-test-secrets.toml"


def _require_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        sys.stderr.write(
            f"error: {name} not set. Get api_id/api_hash from "
            "https://my.telegram.org → 'API development tools', then re-run with:\n"
            f"  export {name}=<value>\n"
        )
        sys.exit(2)
    return value


async def main() -> None:
    api_id = int(_require_env("TELEGRAM_API_ID"))
    api_hash = _require_env("TELEGRAM_API_HASH")

    print(
        dedent(
            """
            This will sign you in as a regular Telegram user (not a bot) and
            save a session string the E2E tests can replay headlessly. Use
            your own phone number; you'll get a code on Telegram (or SMS).
            """
        ).strip()
    )

    client = TelegramClient(StringSession(), api_id, api_hash)
    await client.start()  # interactive: prompts for phone, code, optional 2FA password

    me = await client.get_me()
    session_string = client.session.save()
    await client.disconnect()

    print(f"\nSigned in as: {me.first_name} (id={me.id}, username=@{me.username or '<none>'})")
    print(f"\nSaving session to {SECRETS_FILE} (mode 0600).")

    SECRETS_FILE.write_text(
        dedent(
            f"""\
            # Generated by scripts/telethon_auth.py — DO NOT COMMIT.
            # Treat the session_string as account-takeover material.
            api_id = {api_id}
            api_hash = "{api_hash}"
            session_string = "{session_string}"
            user_id = {me.id}
            """
        )
    )
    SECRETS_FILE.chmod(0o600)

    print(
        dedent(
            f"""

            === Done. ===

            For local test runs, the file at {SECRETS_FILE} is auto-loaded
            by tests/e2e_telegram/conftest.py.

            For CI, export these as repository secrets:
              TELEGRAM_API_ID            = {api_id}
              TELEGRAM_API_HASH          = <copied from env>
              TELEGRAM_SESSION_STRING    = <see {SECRETS_FILE}>
              FINANCE_E2E_BOT_TOKEN      = <your bot's token>
              FINANCE_E2E_BOT_USERNAME   = <your bot's @username>
              FINANCE_E2E_ALLOWED_CHAT   = {me.id}
            """
        ).rstrip()
    )


if __name__ == "__main__":
    asyncio.run(main())
